[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vwm"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
]
